sig_base_path: "/ceph/cms/store/user/aaarora/vbsvvh/preselection/latest/"
bkg_base_path: "/ceph/cms/store/user/aaarora/vbsvvh/preselection/latest/"
data_base_path: "/ceph/cms/store/user/aaarora/vbsvvh/preselection/latest/"

sig_path: ["*r3*3fj_sig*/*1p5*/*.root"]
bkg_path: ["*r3*3fj_bkg*/*/*.root"]
data_path: ["*r3*3fj_data*/*/*.root"]

training_features:
  - met_pt: log
  - met_phi: minmax
  - boosted_h_candidate_pt: log
  - boosted_h_candidate_eta: minmax
  - boosted_h_candidate_phi: minmax
  - boosted_h_candidate_mass: log
  - boosted_h_candidate_tau21: none
  - boosted_v1_candidate_pt: log
  - boosted_v1_candidate_eta: minmax
  - boosted_v1_candidate_phi: minmax
  - boosted_v1_candidate_mass: log
  - boosted_v1_candidate_tau21: none
  - boosted_v2_candidate_pt: log
  - boosted_v2_candidate_eta: minmax
  - boosted_v2_candidate_phi: minmax
  - boosted_v2_candidate_mass: log
  - boosted_v2_candidate_tau21: none

extra_vars:
  - weight
  - boosted_h_candidate_score
  - boosted_v1_candidate_score
  - boosted_v2_candidate_score

constraint_var: "vbs_detajj"

preselection: "(boosted_h_candidate_score >= 0.1) & (boosted_v1_candidate_score >= 0.1) & (boosted_v2_candidate_score >= 0.1)"

learning_rate: 0.0001
batch_size: 4096
n_epochs: 1000

architecture: [64, 32, 16]
bce_weight: 1.0
disco_lambda: 5.0

closure_n_events_min: 10
closure_symmetrize: true
use_batchnorm: true
dropout: 0.2
weight_decay: 0.01
label_smoothing: 0.0

devices: [5]

output: "output/0LEP_3FJ_RUN3"
