sig_base_path: "/home/users/kmohrman/vbs_vvh/ewkcoffea_for_vbs_vvh/ewkcoffea/analysis/vbs_vvh/histos/"
bkg_base_path: "/home/users/kmohrman/vbs_vvh/ewkcoffea_for_vbs_vvh/ewkcoffea/analysis/vbs_vvh/histos/"
data_base_path: "/home/users/kmohrman/vbs_vvh/ewkcoffea_for_vbs_vvh/ewkcoffea/analysis/vbs_vvh/histos/"

sig_path: ["siphontest_jun29_newDY_mHi_00_sig.root"]
bkg_path: ["siphontest_jun29_newDY_mHi_00_bkg.root"]

training_features:
  - njets : minmax,

  - l0_pt : log,
  - l0_eta : minmax,
  - l0_phi : minmax,
  - l1_pt : log,
  - l1_eta : minmax,
  - l1_phi : minmax,

  - fj0_pt : log,
  - fj0_gpt_mass2p : minmax,
  #- fj0_mass : minmax,
  #- fj0_msoftdrop : minmax,
  #- fj0_mparticlenet : minmax,
  - fj0_eta : minmax,
  - fj0_phi : minmax,

  #- fj0_gptHvsQCD : minmax,
  #- fj0_gptWvsQCD : minmax,
  #- fj0_gptZvsQCD : minmax,
  #- fj0_gptVvsQCD : minmax,

  - met : log,
  - metphi : minmax,

  #- vbs_mjj : log,
  - vbs_absdetajj : minmax,
  #- vbs_score : minmax,

  - vbs1_pt : log,
  - vbs2_pt : log,
  - vbs1_eta : minmax,
  - vbs2_eta : minmax,
  - vbs1_phi : minmax,
  - vbs2_phi : minmax,

  - scalarptsum_lepmet : log,
  - scalarptsum_lepmetFJ0 : log,
  - scalarptsum_lepmetvbsFJ0 : log,
  - vectorsum_lepmetvbsFJ0_pt : log,

  - mass_l0l1 : log,
  - dr_l0l1 : minmax ,
  - pt_l0l1 :  log,
  - absdphi_l0l1 : minmax,
  - absdphi_lepmet : minmax,
  - dr_lepmet : minmax,

  - mass_jFJ_min : log,
  - mass_jFJ_max : log,
  - mass_lj_min : log,
  - mass_lj_max : log,

  - absdphi_FJ0lepmet : minmax,
  - nbtagst: minmax,



derived_vars: {}
auto_include_derived_vars: false
auto_include_derived_vars_transform: none

extra_vars:
  - weight

#preselection: "(boosted_h_candidate_score >= 0.1) | (boosted_v_candidate_score >= 0.1)"
#preselection: "nFatJets == 1"

#constraint_var: "mjj_max_any"
constraint_var: "vbs_mjj"
#constraint_var: "vbs_score"
#constraint_var: "fj0_gptZvsQCD"

batch_size: 8192 #16384
learning_rate: 0.01
n_epochs: 5000

early_stopping_patience: 500

architecture: [64, 32, 16]
#architecture: [256, 128, 64, 32]
bce_weight: 1.0
disco_lambda: 30.0
#disco_lambda: 0.0

use_batchnorm: true
dropout: 0.2
weight_decay: 0.01
label_smoothing: 0.0

devices: [2]

output: "2l1FJ_NEW_RUN2"