sig_base_path: "/home/users/kmohrman/vbs_vvh/ewkcoffea_for_vbs_vvh/ewkcoffea/analysis/vbs_vvh/histos/"
bkg_base_path: "/home/users/kmohrman/vbs_vvh/ewkcoffea_for_vbs_vvh/ewkcoffea/analysis/vbs_vvh/histos/"
data_base_path: "/home/users/kmohrman/vbs_vvh/ewkcoffea_for_vbs_vvh/ewkcoffea/analysis/vbs_vvh/histos/"

#sig_path: ["siphontest_jun12_2l_r2_sigSM.root"]
#sig_path: ["siphontest_jun12_2l_r2_sigC2V.root"]
#sig_path: ["siphontest_jun12_2l_r2_sigC3.root"]
sig_path: ["siphontest_jun12_2l_r2_sigSM.root", "siphontest_jun12_2l_r2_sigC2V.root", "siphontest_jun12_2l_r2_sigC3.root"]
bkg_path: ["siphontest_jun12_2l_r2_dy.root", "siphontest_jun12_2l_r2_tt.root"]

training_features:
  #- abs_ch_sum_3l: minmax
  - abs_pdgid_sum: minmax
  - absdeta_max_any: minmax
  #- absdeta_max_fwd: minmax
  - absdphi_j0anyj1any: minmax
  #- absdphi_j0centj1cent: minmax
  #- absdphi_j0fwdj1fwd: minmax
  #- bbscore0_bscore: minmax
  #- bbscore1_bscore: minmax
  - dr_fj0l0: minmax
  #- dr_j0anyj1any: minmax
  #- dr_j0centj1cent: minmax
  #- dr_j0fwdj1fwd: minmax
  - dr_l0l1: minmax
  - dr_lj_max: minmax
  - dr_lj_min: minmax
  #- dr_ljnvbs_max: minmax
  #- dr_ljnvbs_min: minmax
  - fj0_abseta: minmax
  #- fj0_mass: log
  - fj0_mparticlenet: log
  #- fj0_msoftdrop: log
  - fj0_pNetH4qvsQCD: minmax
  - fj0_pNetHbbvsQCD: minmax
  - fj0_pNetHccvsQCD: minmax
  - fj0_pNetQCD: minmax
  - fj0_pNetTvsQCD: minmax
  - fj0_pNetWvsQCD: minmax
  - fj0_pNetZvsQCD: minmax
  - fj0_phi: minmax
  - fj0_pt: log
  - j0any_abseta: minmax
  - j0any_phi: minmax
  - j0any_pt: log
  #- j0central_abseta: minmax
  #- j0central_phi: minmax
  #- j0central_pt: log
  #- j0forward_abseta: minmax
  #- j0forward_phi: minmax
  #- j0forward_pt: log
  #- jbscore0_bscore: minmax
  #- jbscore1_bscore: minmax
  #- jj_pairs_atmindr_mjj: log
  - l0_eta: minmax
  - l0_iso: minmax
  - l0_miniiso: minmax
  - l0_phi: minmax
  - l0_pt: log
  ###- l0_truth: log
  ###- l0_truth_fake_iso: log
  ###- l0_truth_fake_pt: log
  ###- l0_truth_real_iso: log
  ###- l0_truth_real_pt: log
  - l1_eta: minmax
  - l1_iso: minmax
  - l1_miniiso: minmax
  - l1_phi: minmax
  - l1_pt: log
  ###- l1_truth: log
  ###- l1_truth_fake_iso: log
  ###- l1_truth_fake_pt: log
  ###- l1_truth_real_iso: log
  ###- l1_truth_real_pt: log
  ###- l2_eta: minmax
  ###- l2_iso: minmax
  ###- l2_miniiso: minmax
  ###- l2_pt: log
  ###- l2_truth: log
  ###- l2_truth_fake_iso: log
  ###- l2_truth_fake_pt: log
  ###- l2_truth_real_iso: log
  ###- l2_truth_real_pt: log
  #- mass_b0b1: log
  #- mass_bbscore0bbscore1: log
  #- mass_bmbscore0bmbscore1: log
  #- mass_j0anyj1any: log
  #- mass_j0centj1cent: log
  #- mass_j0fwdj1fwd: log
  #- mass_jbscore0jbscore1: log
  #- mass_l0l1: log
  - met: log
  - metphi: minmax
  ###- mjj_max_any: log
  #- mjj_max_cent: log
  #- mjj_max_fwd: log
  #- mjjjall_nearest_t: log
  #- mjjjany: log
  #- mjjjcnt: log
  #- mjjjcnt_nearest_t: log
  #- mjjjjany: log
  #- mjjjjcnt: log
  #- mlb_max: log
  #- mlb_min: log
  #- mljjjany: log
  #- mljjjcnt: log
  #- mljjjjany: log
  #- mljjjjcnt: log
  #- mll_min_afos: log
  - mll_z: log
  #- n_ll_sfos: minmax
  - nbtagsl: minmax
  - nbtagsm: minmax
  - nbtagst: minmax
  #- nfatjets: minmax
  - njets: minmax
  - njets_counts: minmax
  - njets_forward: minmax
  - njets_tot: minmax
  ###- nlep_truth_fake: minmax
  ###- nlep_truth_real: minmax
  #- nleps: minmax
  #- nleps_counts: minmax
  - scalarptsum_jetCent: log
  - scalarptsum_jetCentFwd: log
  - scalarptsum_jetFwd: log
  - scalarptsum_lep: log
  - scalarptsum_lepmet: log
  - scalarptsum_lepmetFJ: log
  - scalarptsum_lepmetFJ10: log
  - scalarptsum_lepmetalljets: log
  - scalarptsum_lepmetcentjets: log
  - scalarptsum_lepmetfwdjets: log
  - vbs_absdetajj: minmax
  - vbs_mjj: log
  - vbs_score: minmax


derived_vars: {}
auto_include_derived_vars: false
auto_include_derived_vars_transform: none

extra_vars:
  - weight

#preselection: "(boosted_h_candidate_score >= 0.1) | (boosted_v_candidate_score >= 0.1)"
#preselection: "nFatJets == 1"

constraint_var: "mjj_max_any"

batch_size: 8192 #16384
learning_rate: 0.0001
n_epochs: 1000

architecture: [64, 32, 16]
bce_weight: 1.0
#disco_lambda: 10.0
#disco_lambda: 100.0
disco_lambda: 0.0

use_batchnorm: true
dropout: 0.2
weight_decay: 0.01
label_smoothing: 0.0

devices: [2]

output: "2l1FJ_NEW_RUN2"
